# Generated by Django 3.1.3 on 2022-09-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_idx', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.CharField(max_length=25)),
                ('admin_pw', models.CharField(max_length=25)),
                ('admin_name', models.CharField(max_length=20)),
                ('admin_department_no', models.IntegerField()),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('bas_idx', models.AutoField(primary_key=True, serialize=False)),
                ('bas_user_no', models.IntegerField(blank=True, null=True)),
                ('bas_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'basket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_idx', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryA',
            fields=[
                ('a_idx', models.AutoField(db_column='A_idx', primary_key=True, serialize=False)),
                ('a_name', models.CharField(blank=True, db_column='A_name', max_length=10, null=True)),
            ],
            options={
                'db_table': 'category_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryB',
            fields=[
                ('b_idx', models.AutoField(db_column='B_idx', primary_key=True, serialize=False)),
                ('b_name', models.CharField(blank=True, db_column='B_name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'category_b',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('del_idx', models.AutoField(primary_key=True, serialize=False)),
                ('del_name', models.CharField(max_length=50)),
                ('del_tel1', models.CharField(max_length=20)),
                ('del_tel2', models.CharField(max_length=20)),
                ('del_add_no', models.CharField(max_length=6)),
                ('del_addr', models.CharField(max_length=50)),
                ('del_addr_plus', models.CharField(max_length=50)),
                ('del_order_text', models.CharField(blank=True, max_length=100, null=True)),
                ('del_cod', models.IntegerField(blank=True, null=True)),
                ('del_cost', models.IntegerField(blank=True, null=True)),
                ('del_situ', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_num', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(blank=True, max_length=50, null=True)),
                ('goods_c_price', models.IntegerField()),
                ('goods_sale_price', models.IntegerField(db_column='goods_Sale_price')),
                ('goods_info', models.FileField(blank=True, null=True, upload_to='')),
                ('goods_image', models.FileField(blank=True, null=True, upload_to='')),
                ('goods_stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_idx', models.AutoField(primary_key=True, serialize=False)),
                ('pay_paymethod_no', models.IntegerField(blank=True, null=True)),
                ('pay_card_num', models.CharField(blank=True, max_length=30, null=True)),
                ('pay_amount', models.IntegerField(blank=True, null=True)),
                ('pay_price', models.IntegerField(blank=True, null=True)),
                ('pay_join_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('re_idx', models.AutoField(primary_key=True, serialize=False)),
                ('re_return_date', models.DateField(blank=True, null=True)),
                ('re_return_reason', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'returns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(blank=True, max_length=20, null=True)),
                ('s_situ', models.CharField(blank=True, max_length=20, null=True)),
                ('s_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'salary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ttable',
            fields=[
                ('t_no', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(blank=True, max_length=20, null=True)),
                ('t_money', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ttable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uploadfilesmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='')),
                ('upload_filename', models.CharField(blank=True, max_length=64, null=True)),
                ('upload_content_type', models.CharField(blank=True, max_length=128, null=True)),
                ('upload_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uploadfilesmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uploadmodel',
            fields=[
                ('up_no', models.AutoField(primary_key=True, serialize=False)),
                ('up_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'uploadmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=25)),
                ('user_pw', models.CharField(max_length=25)),
                ('join_date', models.DateField()),
                ('addr', models.CharField(blank=True, max_length=100, null=True)),
                ('home_num', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('point', models.IntegerField()),
                ('e_agreement', models.IntegerField(blank=True, null=True)),
                ('n_agreement', models.IntegerField(blank=True, null=True)),
                ('p_agreement', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
