# Generated by Django 3.1.3 on 2022-09-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('logtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('not_num', models.AutoField(primary_key=True, serialize=False)),
                ('not_title', models.CharField(blank=True, max_length=20, null=True)),
                ('not_content', models.TextField(blank=True, null=True)),
                ('not_write_date', models.DateField(auto_now_add=True)),
                ('not_hits', models.IntegerField(blank=True, null=True)),
                ('not_checks', models.BooleanField(default=False, verbose_name='상단고정')),
                ('not_sort', models.IntegerField(default=0, verbose_name='고정정렬')),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('q_num', models.AutoField(db_column='Q_num', primary_key=True, serialize=False)),
                ('q_group_no', models.IntegerField(default=0)),
                ('q_order_no', models.IntegerField(default=0)),
                ('q_depth', models.IntegerField(default=0)),
                ('q_title', models.CharField(blank=True, db_column='Q_Title', max_length=100, null=True)),
                ('q_text', models.TextField(db_column='Q_Text')),
                ('q_w_date', models.DateTimeField(auto_now_add=True, db_column='Q_W_date')),
                ('q_hits', models.IntegerField(blank=True, db_column='Q_Hits', null=True)),
                ('answer', models.IntegerField(blank=True, db_column='Answer', null=True)),
            ],
            options={
                'db_table': 'qna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rev_no', models.AutoField(primary_key=True, serialize=False)),
                ('rev_title', models.CharField(max_length=20)),
                ('rev_afterword', models.TextField()),
                ('rev_use_date', models.DateField(auto_now_add=True)),
                ('rev_view_count', models.IntegerField()),
                ('rev_hit_use', models.IntegerField()),
                ('rev_use', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
